import 'package:foodtek/core/utils/app_image_strings.dart';

final List<Map<String, dynamic>> allDummyItems = [
  {
    'id': 'pizza_0',
    'title': 'Pepperoni Pizza',
    'description': 'With spicy pepperoni',
    'price': 10.0,
    'imagePath': AppImageStrings.pepperoniPizza,
  },
  {
    'id': 'pizza_1',
    'title': 'Cheese Pizza',
    'description': 'Cheesy goodness',
    'price': 8.0,
    'imagePath': AppImageStrings.cheesePizza,
  },
  {
    'id': 'pizza_2',
    'title': 'Peppy Paneer',
    'description': 'Loaded with veggies',
    'price': 9.0,
    'imagePath': AppImageStrings.peppyPaneerPizza,
  },
  {
    'id': 'pizza_3',
    'title': 'Mexican Green Wave',
    'description': 'Sweet BBQ sauce',
    'price': 11.0,
    'imagePath': AppImageStrings.mexicanGreenWavePizza,
  },
  {
    'id': 'burger_0',
    'title': 'Classic Burger',
    'description': '100% Beef patty',
    'price': 5.0,
    'imagePath': AppImageStrings.chickenBurger,
  },
  {
    'id': 'burger_1',
    'title': 'Cheese Delight',
    'description': 'Loaded with cheese',
    'price': 6.0,
    'imagePath': AppImageStrings.cheeseBurger,
  },
  {
    'id': 'burger_2',
    'title': 'Spicy Chicken',
    'description': 'Hot and spicy',
    'price': 5.5,
    'imagePath': AppImageStrings.chickenBurger,
  },
  {
    'id': 'burger_3',
    'title': 'Veggie Burger',
    'description': 'Fresh veggies',
    'price': 4.5,
    'imagePath': AppImageStrings.cheeseBurger,
  },
  {
    'id': 'sandwich_0',
    'title': 'Ham & Cheese',
    'description': 'Classic favorite',
    'price': 3.5,
    'imagePath': AppImageStrings.sandwich,
  },
  {
    'id': 'sandwich_1',
    'title': 'Chicken Sandwich',
    'description': 'Grilled chicken',
    'price': 4.5,
    'imagePath': AppImageStrings.sandwich,
  },
  {
    'id': 'sandwich_2',
    'title': 'Veggie Sandwich',
    'description': 'Fresh vegetables',
    'price': 3.0,
    'imagePath': AppImageStrings.sandwich,
  },
  {
    'id': 'sandwich_3',
    'title': 'Egg Sandwich',
    'description': 'Boiled eggs',
    'price': 2.5,
    'imagePath': AppImageStrings.sandwich,
  },
];
