import '../constants/app_image_strings.dart';
import '../models/food_model.dart';

final List<FoodModel> dummyFoods = [
  FoodModel(
    id: 'f1',
    name: 'Monetize Synergistic Metrics',
    description: 'Young fall fill page.',
    originalPrice: 6.14,
    discountedPrice: 5.33,
    rating: 4.4,
    image: AppImageStrings.mexicanGreenWavePizza,
    category: FoodCategory.pizza,
    isTopRated: true,
    isRecommended: true,
    spiceLevel: 1,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 144,
  ),
  FoodModel(
    id: 'f2',
    name: 'Maximize Killer Convergence',
    description: 'Fact pretty prepare dark third American.',
    originalPrice: 5.01,
    discountedPrice: null,
    rating: 3.9,
    image: AppImageStrings.peppyPaneerPizza,
    category: FoodCategory.pizza,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 159,
  ),
  FoodModel(
    id: 'f3',
    name: 'Generate E-Business Schemas',
    description: 'Bill price example population.',
    originalPrice: 5.11,
    discountedPrice: null,
    rating: 4.3,
    image: AppImageStrings.pepperoniPizza,
    category: FoodCategory.burger,
    isTopRated: false,
    isRecommended: false,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 114,
  ),
  FoodModel(
    id: 'f4',
    name: 'Leverage Value-Added Interfaces',
    description: 'Trouble sister memory over pay.',
    originalPrice: 8.57,
    discountedPrice: 3.63,
    rating: 3.9,
    image: AppImageStrings.pepperoniPizza,
    category: FoodCategory.sandwich,
    isTopRated: true,
    isRecommended: false,
    spiceLevel: 4,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 95,
  ),
  FoodModel(
    id: 'f5',
    name: 'Facilitate Magnetic Synergies',
    description: 'As attack pay fight.',
    originalPrice: 5.32,
    discountedPrice: null,
    rating: 3.6,
    image: AppImageStrings.chickenBurger,
    category: FoodCategory.burger,
    isTopRated: true,
    isRecommended: false,
    spiceLevel: 2,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 98,
  ),
  FoodModel(
    id: 'f6',
    name: 'Incentivize Proactive Niches',
    description: 'Cover question but moment pay still institution.',
    originalPrice: 8.62,
    discountedPrice: 3.67,
    rating: 3.6,
    image: AppImageStrings.chickenBurger,
    category: FoodCategory.sandwich,
    isTopRated: true,
    isRecommended: true,
    spiceLevel: 2,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 54,
  ),
  FoodModel(
    id: 'f7',
    name: 'Implement Interactive Users',
    description: 'Note front forward truth support fill.',
    originalPrice: 8.83,
    discountedPrice: null,
    rating: 3.6,
    image: AppImageStrings.pepperoniPizza,
    category: FoodCategory.sandwich,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 190,
  ),
  FoodModel(
    id: 'f8',
    name: 'E-Enable Cross-Platform Bandwidth',
    description: 'Commercial partner our across forward really check cold.',
    originalPrice: 5.65,
    discountedPrice: 6.35,
    rating: 3.7,
    image: AppImageStrings.chickenBurger,
    category: FoodCategory.sandwich,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 109,
  ),
  FoodModel(
    id: 'f9',
    name: 'Harness Out-Of-The-Box Interfaces',
    description: 'Power discover notice focus wall what move.',
    originalPrice: 6.46,
    discountedPrice: 4.07,
    rating: 4.7,
    image: AppImageStrings.pepperoniPizza,
    category: FoodCategory.burger,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 1,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 113,
  ),
  FoodModel(
    id: 'f10',
    name: 'Facilitate Robust Synergies',
    description: 'Yeah measure law soldier media.',
    originalPrice: 8.01,
    discountedPrice: null,
    rating: 3.5,
    image: AppImageStrings.mexicanGreenWavePizza,
    category: FoodCategory.sandwich,
    isTopRated: true,
    isRecommended: false,
    spiceLevel: 2,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 103,
  ),
  FoodModel(
    id: 'f11',
    name: 'Leverage Out-Of-The-Box Synergies',
    description: 'Join life end run both over.',
    originalPrice: 7.02,
    discountedPrice: null,
    rating: 4.5,
    image: AppImageStrings.pepperoniPizza,
    category: FoodCategory.sandwich,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 182,
  ),
  FoodModel(
    id: 'f12',
    name: 'Engage Granular Info-Mediaries',
    description: 'Final fly close every along local.',
    originalPrice: 8.27,
    discountedPrice: 7.17,
    rating: 4.9,
    image: AppImageStrings.cheeseBurger,
    category: FoodCategory.pizza,
    isTopRated: true,
    isRecommended: false,
    spiceLevel: 1,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 154,
  ),
  FoodModel(
    id: 'f13',
    name: 'Cultivate Dynamic Solutions',
    description: 'Wind act image remain stand effort perform.',
    originalPrice: 5.52,
    discountedPrice: 6.17,
    rating: 4.7,
    image: AppImageStrings.mexicanGreenWavePizza,
    category: FoodCategory.burger,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 3,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 102,
  ),
  FoodModel(
    id: 'f14',
    name: 'Engineer Intuitive Web Services',
    description: 'None amount range suffer either.',
    originalPrice: 7.19,
    discountedPrice: null,
    rating: 3.5,
    image: AppImageStrings.peppyPaneerPizza,
    category: FoodCategory.pizza,
    isTopRated: false,
    isRecommended: false,
    spiceLevel: 4,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 51,
  ),
  FoodModel(
    id: 'f15',
    name: 'Exploit Cutting-Edge Schemas',
    description: 'Industry spring central turn reach.',
    originalPrice: 6.43,
    discountedPrice: 3.9,
    rating: 4.5,
    image: AppImageStrings.chickenBurger,
    category: FoodCategory.pizza,
    isTopRated: true,
    isRecommended: false,
    spiceLevel: 1,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 186,
  ),
  FoodModel(
    id: 'f16',
    name: 'Brand Viral Infrastructures',
    description: 'Next rise almost child just inside here fish.',
    originalPrice: 7.73,
    discountedPrice: 6.58,
    rating: 4.2,
    image: AppImageStrings.cheesePizza,
    category: FoodCategory.pizza,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 96,
  ),
  FoodModel(
    id: 'f17',
    name: 'Innovate Vertical Niches',
    description: 'Yes third environmental itself woman wife possible respond.',
    originalPrice: 5.95,
    discountedPrice: 4.83,
    rating: 3.6,
    image: AppImageStrings.peppyPaneerPizza,
    category: FoodCategory.sandwich,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 4,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 62,
  ),
  FoodModel(
    id: 'f18',
    name: 'Engage Distributed Synergies',
    description: 'Unit amount view stop office task.',
    originalPrice: 7.14,
    discountedPrice: 6.35,
    rating: 4.5,
    image: AppImageStrings.cheesePizza,
    category: FoodCategory.sandwich,
    isTopRated: true,
    isRecommended: true,
    spiceLevel: 3,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 106,
  ),
  FoodModel(
    id: 'f19',
    name: 'Embrace Clicks-And-Mortar Methodologies',
    description: 'Knowledge finish return.',
    originalPrice: 6.0,
    discountedPrice: 5.2,
    rating: 4.8,
    image: AppImageStrings.chickenBurger,
    category: FoodCategory.sandwich,
    isTopRated: true,
    isRecommended: false,
    spiceLevel: 2,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 192,
  ),
  FoodModel(
    id: 'f20',
    name: 'Brand Scalable Content',
    description: 'Home education as tree.',
    originalPrice: 6.49,
    discountedPrice: null,
    rating: 4.3,
    image: AppImageStrings.peppyPaneerPizza,
    category: FoodCategory.pizza,
    isTopRated: false,
    isRecommended: true,
    spiceLevel: 0,
    inCartQuantity: 0,
    orderedAt: null,
    orderedCount: 120,
  ),
];
